import io
from datetime import date, datetime, timezone
from unittest.mock import AsyncMock, patch
from uuid import uuid4

import pytest
from openpyxl import Workbook, load_workbook

from app.crud.excel_export_crud import ReportLineAllocationDetail, ReportLineExpense
from app.models.budget import BudgetCategoryModel, BudgetLineModel, BudgetModel
from app.schemas.budget_schema import BudgetStatus
from app.services.excel_export_service import (
    SHEET3_TITLE,
    DashboardSheet,
    ExpenseListSheet,
    _audit_line,
    _build_expense_rows,
    _period_label,
    generate_budget_export_workbook,
)
from tests.factories.budget import BudgetCategoryFactory, BudgetFactory, BudgetLineFactory
from tests.factories.currency_ledger import CurrencyConversionFactory, FundingReceiptFactory

OWNER_ID = str(uuid4())
FUNDER_ID = str(uuid4())
STRANGER_ID = str(uuid4())


class TestPeriodLabel:
    def test_none_start_date_returns_none(self):
        assert _period_label(None, 12) is None

    def test_formats_start_and_computed_end_month(self):
        assert _period_label(date(2026, 1, 1), 12) == "01/2026-12/2026"

    def test_no_duration_shows_start_month_only(self):
        assert _period_label(date(2026, 3, 15), None) == "03/2026"

    def test_zero_duration_shows_start_month_only(self):
        """0 is BudgetModel.duration_months's column default — same "unknown" case as None."""
        assert _period_label(date(2026, 3, 15), 0) == "03/2026"


class TestAuditLine:
    def test_includes_user_and_timestamp_when_both_known(self):
        exported_at = datetime(2026, 9, 22, 14, 30, tzinfo=timezone.utc)
        assert (
            _audit_line("a@b.com", exported_at)
            == "Generated by OpenGrantFlow · a@b.com · 2026-09-22 14:30 UTC"
        )

    def test_omits_missing_parts(self):
        assert _audit_line(None, None) == "Generated by OpenGrantFlow"


class TestBuildExpenseRows:
    def test_fully_allocated_uses_real_rate_not_estimated(self):
        line = BudgetLineFactory.build(description="Salaries")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Rent",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 1
        assert rows[0].amount == 100.0
        assert rows[0].rate == 2.0
        assert rows[0].is_estimated is False

    def test_partial_allocation_remainder_uses_estimated_rate(self):
        line = BudgetLineFactory.build(description="Flights")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=60.0,
                )
            ],
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 2
        assert rows[0].amount == 60.0
        assert rows[0].rate == 2.0
        assert rows[0].is_estimated is False
        assert rows[1].amount == 40.0
        assert rows[1].rate == 2.0
        assert rows[1].is_estimated is True
        assert rows[1].conversion_date is None

    def test_fully_unallocated_uses_estimated_rate_for_full_amount(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 1
        assert rows[0].amount == 100.0
        assert rows[0].rate == 2.0
        assert rows[0].is_estimated is True

    def test_no_estimated_rate_leaves_remainder_unrated(self):
        """No fabrication when the budget itself has no rate to fall back on."""
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=None)

        assert rows[0].rate is None
        assert rows[0].is_estimated is False

    def test_category_name_looked_up_from_budget_line(self):
        category = BudgetCategoryFactory.build(name="Travel")
        line = BudgetLineFactory.build(
            description="Flights", category=category, category_id=category.id
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [category], [expense], estimated_exchange_rate=None)

        assert rows[0].category_name == "Travel"

    def test_refund_keeps_its_negative_row(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Refund",
            amount=-500.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 1
        assert rows[0].amount == -500.0
        assert rows[0].rate == 2.0
        assert rows[0].is_estimated is True

    def test_zero_amount_unallocated_expense_keeps_its_row(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Waived",
            amount=0.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=None)

        assert len(rows) == 1
        assert rows[0].amount == 0.0

    def test_over_allocation_adds_negative_remainder_so_rows_sum_to_amount(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=120.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=60.0,
                    conversion_local_amount=120.0,
                )
            ],
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert [row.amount for row in rows] == [120.0, -20.0]
        assert sum(row.amount for row in rows) == 100.0

    def test_fully_allocated_expense_adds_no_remainder_row(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 1

    def test_zero_estimated_rate_leaves_remainder_unrated(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=0.0)

        assert rows[0].rate is None
        assert rows[0].is_estimated is False

    def test_zero_local_amount_conversion_leaves_allocation_unrated(self):
        line = BudgetLineFactory.build(description="Fee")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Fee",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=0.0,
                )
            ],
        )

        rows = _build_expense_rows([line], [], [expense], estimated_exchange_rate=2.0)

        assert len(rows) == 1
        assert rows[0].rate is None


class TestDashboardSheet:
    def _write(
        self,
        budget,
        categories=(),
        lines=(),
        expenses=(),
        receipts=(),
        conversions=(),
        exported_by=None,
        exported_at=None,
    ):
        wb = Workbook()
        ws = wb.active
        expense_rows = _build_expense_rows(
            list(lines), list(categories), list(expenses), budget.estimated_exchange_rate
        )
        DashboardSheet(
            ws,
            budget,
            "Test Org",
            "Test Donor",
            list(receipts),
            list(conversions),
            list(categories),
            list(lines),
            expense_rows,
            exported_by,
            exported_at,
        ).write()
        return ws

    def test_full_layout_with_rate(self):
        confirmed_at = datetime(2026, 1, 10, tzinfo=timezone.utc)
        budget = BudgetFactory.build(
            local_currency="GBP",
            actual_currency="USD",
            estimated_exchange_rate=2.0,
            confirmed_at=confirmed_at,
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Personnel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Salaries",
            amount=1000.0,
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Payroll",
            amount=100.0,
            expense_date=date(2026, 2, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 1, 20),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )
        receipt = FundingReceiptFactory.build(amount=600.0, received_at=date(2026, 1, 1))
        conversion = CurrencyConversionFactory.build(
            donor_amount=300.0, local_amount=650.0, converted_at=date(2026, 1, 2)
        )
        exported_at = datetime(2026, 9, 22, 14, 30, tzinfo=timezone.utc)

        ws = self._write(
            budget,
            categories=[category],
            lines=[line],
            expenses=[expense],
            receipts=[receipt],
            conversions=[conversion],
            exported_by="exporter@example.com",
            exported_at=exported_at,
        )
        rows = list(ws.iter_rows(values_only=True))

        assert rows[0][:2] == ("Organisation Name", "Test Org")
        assert rows[1][:2] == ("Donor Name", "Test Donor")

        # column widths wide enough for the longest header in each ("Total Expenses (USD)" etc)
        assert ws.column_dimensions["A"].width == 26.63
        assert ws.column_dimensions["B"].width == 18.0
        assert ws.column_dimensions["C"].width == 21.0
        assert ws.column_dimensions["D"].width == 21.0
        assert ws.column_dimensions["E"].width == 23.0
        assert ws.column_dimensions["F"].width == 18.0

        assert rows[7][:2] == ("Approved Total", 500.0)  # 1000 GBP / rate 2.0
        assert ws.cell(row=9, column=1).value == "Approved on"
        assert ws.cell(row=9, column=2).value == confirmed_at.replace(tzinfo=None)

        assert rows[10][:3] == ("Received Total", 600.0, "=B11/B8")
        assert rows[11][:3] == ("Converted Total", 300.0, "=B12/B11")
        assert rows[12][:3] == ("Current Balance", "USD", "GBP")
        assert ws.cell(row=14, column=2).value == "=B11-B12"
        assert ws.cell(row=14, column=3).value == 550.0  # 650 converted - 100 spent, local

        assert rows[15][:1] == ("Funding Ledger",)
        assert rows[16][:5] == (
            "Date",
            "Received",
            "Donor Amount (USD)",
            "Local Amount (GBP)",
            "Implied Rate",
        )
        assert rows[17][:5] == (date(2026, 1, 1), 600.0, None, None, None)
        assert rows[18][:5] == (date(2026, 1, 2), None, 300.0, 650.0, "=D19/C19")
        assert rows[19][:5] == ("TOTAL", None, "=SUM(C18:C19)", "=SUM(D18:D19)", None)

        assert rows[22][:6] == (
            "Report Summary",
            "Original (USD)",
            "Planned (GBP)",
            "Expenses (GBP)",
            "Total Expenses (USD)",
            "Deviation (USD)",
        )
        assert rows[23][:6] == ("Personnel", "=B29", "=C29", "=D29", "=E29", "=F29")
        assert rows[24][:6] == (
            "TOTAL",
            "=SUM(B24:B24)",
            "=SUM(C24:C24)",
            "=SUM(D24:D24)",
            "=SUM(E24:E24)",
            "=SUM(F24:F24)",
        )

        assert rows[26][0] == "Personnel"
        assert ws.cell(row=28, column=1).value == "Salaries"
        assert ws.cell(row=28, column=2).value == 500.0
        assert ws.cell(row=28, column=3).value == 1000.0
        assert ws.cell(row=28, column=4).value == (
            f"=SUMIF('{SHEET3_TITLE}'!$I:$I,$H28,'{SHEET3_TITLE}'!$E:$E)"
        )
        assert ws.cell(row=28, column=5).value == (
            f"=SUMIF('{SHEET3_TITLE}'!$I:$I,$H28,'{SHEET3_TITLE}'!$F:$F)"
        )
        assert ws.cell(row=28, column=6).value == "=B28-E28"
        assert ws.cell(row=28, column=8).value == str(line.id)
        assert rows[28][:6] == (
            "Subtotal",
            "=SUM(B28:B28)",
            "=SUM(C28:C28)",
            "=SUM(D28:D28)",
            "=SUM(E28:E28)",
            "=SUM(F28:F28)",
        )
        converted_cell = ws.cell(row=28, column=5)
        assert converted_cell.font.italic is not True  # fully allocated -> no estimate style

        assert rows[33][:2] == ("Refund to donor:", "=B11-E25")
        assert ws.cell(row=38, column=2).border.bottom.style == "thin"  # Place, date: line
        assert ws.cell(row=42, column=1).border.bottom.style == "thin"
        assert ws.cell(row=42, column=2).border.bottom.style == "thin"
        assert ws.cell(row=42, column=4).border.bottom.style == "thin"
        assert ws.cell(row=42, column=5).border.bottom.style == "thin"
        assert rows[42][:1] == ("Authorised Signatory",)
        assert rows[42][3] == "Project Contact Person"
        assert rows[46][0] == (
            "Generated by OpenGrantFlow · exporter@example.com · 2026-09-22 14:30 UTC"
        )

    def test_partially_allocated_line_is_styled_as_estimate(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Travel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Flights",
            amount=500.0,
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=60.0,
                )
            ],
        )

        ws = self._write(budget, categories=[category], lines=[line], expenses=[expense])

        # real 60 local/30 donor (rate 2.0) + estimated remainder 40/2.0 -> blended donor total
        converted_cell = ws.cell(row=26, column=5)
        assert converted_cell.value == (
            f"=SUMIF('{SHEET3_TITLE}'!$I:$I,$H26,'{SHEET3_TITLE}'!$F:$F)"
        )
        assert converted_cell.font.italic is True
        assert converted_cell.fill.fgColor.rgb == "00FFF2CC"
        assert ws.cell(row=26, column=7).value == "*"
        assert ws.cell(row=26, column=7).font.color.rgb == "00FF0000"

    def test_estimate_flag_adds_footnote_above_audit_line(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Travel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Flights",
            amount=500.0,
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=60.0,
                )
            ],
        )

        ws = self._write(budget, categories=[category], lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[42][:2] == (
            "*",
            "Highlighted amount includes an estimate — the budget's estimated exchange rate "
            "applied to the portion not yet linked to a currency conversion.",
        )
        assert ws.cell(row=43, column=1).font.color.rgb == "00FF0000"
        assert ws.cell(row=43, column=2).font.color.rgb == "00808080"
        assert rows[44][0] == "Generated by OpenGrantFlow"

    def test_no_estimate_flag_omits_footnote(self):
        """Fully-allocated line: no estimate anywhere, so the row/footnote stay absent
        and the audit line keeps its original (unshifted) position."""
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Travel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Flights",
            amount=500.0,
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 3, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 2, 1),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )

        ws = self._write(budget, categories=[category], lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert ws.cell(row=26, column=7).value is None
        assert rows[42] == (None,) * 8
        assert rows[44][0] == "Generated by OpenGrantFlow"

    def test_no_rate_leaves_donor_columns_blank(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=None
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Travel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Flights",
            amount=500.0,
        )

        ws = self._write(budget, categories=[category], lines=[line])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[7][:2] == ("Approved Total", None)
        assert rows[25][:3] == ("Flights", None, 500.0)
        assert rows[25][3] == f"=SUMIF('{SHEET3_TITLE}'!$I:$I,$H26,'{SHEET3_TITLE}'!$E:$E)"
        assert rows[25][4:6] == (None, None)

    def test_no_categories_or_ledger_events_falls_back_to_header_plus_one(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")

        ws = self._write(budget)
        rows = list(ws.iter_rows(values_only=True))

        assert rows[16][:5] == (
            "Date",
            "Received",
            "Donor Amount (USD)",
            "Local Amount (GBP)",
            "Implied Rate",
        )
        assert rows[17][:5] == ("TOTAL", None, 0.0, 0.0, None)  # ledger_total_row = header+1
        assert rows[20][0] == "Report Summary"
        assert rows[21][0] == "TOTAL"  # report_summary_total_row = header+1, no categories

    def test_no_approved_total_skips_received_percent(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        receipt = FundingReceiptFactory.build(amount=600.0, received_at=date(2026, 1, 1))

        ws = self._write(budget, receipts=[receipt])

        assert ws.cell(row=11, column=3).value is None

    def test_tz_aware_confirmed_at_does_not_break_save(self):
        # openpyxl rejects tz-aware datetimes only at wb.save() time, not at cell-write
        # time — a bare ws.cell() assertion would miss this; must round-trip through save.
        budget = BudgetFactory.build(
            local_currency="GBP",
            actual_currency="USD",
            confirmed_at=datetime(2026, 1, 10, tzinfo=timezone.utc),
        )
        wb = Workbook()
        ws = wb.active
        DashboardSheet(ws, budget, "Org", "Donor", [], [], [], [], [], None, None).write()

        buf = io.BytesIO()
        wb.save(buf)
        reloaded = load_workbook(buf)["Sheet"]
        assert reloaded.cell(row=9, column=2).value == datetime(2026, 1, 10)


class TestExpenseListSheet:
    def _write(
        self, budget, categories=(), lines=(), expenses=(), exported_by=None, exported_at=None
    ):
        wb = Workbook()
        ws = wb.active
        rows = _build_expense_rows(
            list(lines), list(categories), list(expenses), budget.estimated_exchange_rate
        )
        ExpenseListSheet(
            ws, budget, "Test Org", "Test Donor", rows, exported_by, exported_at
        ).write()
        return ws

    def test_unallocated_expense_has_no_conversion_info(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="June rent",
            amount=100.0,
            expense_date=date(2026, 6, 1),
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[0] == (
            "Date",
            "Category",
            "Budget Line",
            "Description",
            "Amount (GBP)",
            "Converted Amount (USD)",
            "Exchange rate",
            "Exchange date",
            "Budget Line ID",
        )
        assert rows[1] == (
            date(2026, 6, 1), None, "Travel", "June rent", 100.0, None, None, "*", str(line.id)
        )
        assert rows[2] == ("Total", None, None, None, "=SUM(E2:E2)", None, None, None, None)
        assert rows[3] == (None,) * 9
        assert rows[4] == (
            "*",
            "Converted amount and exchange rate omitted — 1 of 1 expense row(s) "
            "not yet converted to USD.",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        )
        assert rows[5] == (None,) * 9
        assert rows[6][0] == "Generated by OpenGrantFlow"

    def test_single_lot_expense_shows_its_rate_and_date(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Flight",
            amount=100.0,
            expense_date=date(2026, 6, 2),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 5, 30),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[1] == (
            date(2026, 6, 2),
            None,
            "Travel",
            "Flight",
            100.0,
            "=E2/G2",
            2.0,
            date(2026, 5, 30),
            str(line.id),
        )
        assert rows[2] == (
            "Total", None, None, None, "=SUM(E2:E2)", "=SUM(F2:F2)", "=E3/F3", None, None
        )
        assert ws.cell(row=2, column=1).border.top.style == "thin"
        assert ws.cell(row=2, column=8).border.bottom.style == "thin"

    def test_multi_lot_expense_rows_sum_to_full_amount(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Hotel",
            amount=150.0,
            expense_date=date(2026, 6, 3),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 5, 1),
                    conversion_donor_amount=40.0,
                    conversion_local_amount=100.0,
                ),
                ReportLineAllocationDetail(
                    amount_allocated=50.0,
                    converted_at=date(2026, 5, 15),
                    conversion_donor_amount=20.0,
                    conversion_local_amount=50.0,
                ),
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[1] == (
            date(2026, 6, 3),
            None,
            "Travel",
            "Hotel",
            100.0,
            "=E2/G2",
            2.5,
            date(2026, 5, 1),
            str(line.id),
        )
        assert rows[2] == (
            date(2026, 6, 3),
            None,
            "Travel",
            "Hotel",
            50.0,
            "=E3/G3",
            2.5,
            date(2026, 5, 15),
            str(line.id),
        )
        assert rows[1][4] + rows[2][4] == expense.amount
        assert rows[3] == (
            "Total", None, None, None, "=SUM(E2:E3)", "=SUM(F2:F3)", "=E4/F4", None, None
        )

    def test_single_partial_allocation_adds_unrated_remainder_row(self):
        """A single allocation short of the full amount must not be shown as if it
        covered the whole expense — the gap gets its own unrated row instead."""
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Taxi",
            amount=150.0,
            expense_date=date(2026, 6, 4),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 5, 20),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=60.0,
                )
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[1] == (
            date(2026, 6, 4),
            None,
            "Travel",
            "Taxi",
            60.0,
            "=E2/G2",
            2.0,
            date(2026, 5, 20),
            str(line.id),
        )
        assert rows[2] == (
            date(2026, 6, 4), None, "Travel", "Taxi", 90.0, None, None, "*", str(line.id)
        )
        assert rows[1][4] + rows[2][4] == expense.amount
        assert rows[3] == (
            "Total", None, None, None, "=SUM(E2:E3)", "=SUM(F2:F3)", None, None, None
        )
        assert rows[4] == (None,) * 9
        assert rows[5] == (
            "*",
            "Exchange rate omitted — 1 of 2 expense row(s) not yet converted to USD.",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        )
        assert rows[6] == (None,) * 9
        assert rows[7][0] == "Generated by OpenGrantFlow"
        assert ws.cell(row=3, column=8).font.color.rgb == "00FF0000"
        assert ws.cell(row=6, column=1).font.color.rgb == "00FF0000"
        assert ws.cell(row=6, column=2).font.color.rgb == "00808080"

    def test_single_partial_allocation_remainder_uses_estimated_rate_when_available(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Taxi",
            amount=150.0,
            expense_date=date(2026, 6, 4),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 5, 20),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=60.0,
                )
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[2] == (
            date(2026, 6, 4), None, "Travel", "Taxi", 90.0, "=E3/G3", 2.0, "*", str(line.id)
        )
        assert rows[3] == (
            "Total", None, None, None, "=SUM(E2:E3)", "=SUM(F2:F3)", "=E4/F4", None, None
        )
        assert rows[5] == (
            "*",
            "Amount and exchange rate estimated using the budget's estimated exchange rate "
            "— 1 of 2 expense row(s) not yet linked to a currency conversion to USD.",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        )
        assert ws.cell(row=3, column=8).font.color.rgb == "00FF0000"  # star marker, no real date

    def test_multi_allocation_partial_adds_unrated_remainder_row(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Conference",
            amount=300.0,
            expense_date=date(2026, 6, 5),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 5, 1),
                    conversion_donor_amount=40.0,
                    conversion_local_amount=100.0,
                ),
                ReportLineAllocationDetail(
                    amount_allocated=80.0,
                    converted_at=date(2026, 5, 15),
                    conversion_donor_amount=32.0,
                    conversion_local_amount=80.0,
                ),
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[1][4] == 100.0
        assert rows[2][4] == 80.0
        assert rows[3] == (
            date(2026, 6, 5), None, "Travel", "Conference", 120.0, None, None, "*", str(line.id)
        )
        assert rows[1][4] + rows[2][4] + rows[3][4] == expense.amount
        assert rows[4] == (
            "Total", None, None, None, "=SUM(E2:E4)", "=SUM(F2:F4)", None, None, None
        )
        assert rows[5] == (None,) * 9
        assert rows[6] == (
            "*",
            "Exchange rate omitted — 1 of 3 expense row(s) not yet converted to USD.",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        )
        assert rows[7] == (None,) * 9
        assert rows[8][0] == "Generated by OpenGrantFlow"

    def test_category_column_shows_budget_lines_category(self):
        budget = BudgetFactory.build(local_currency="GBP", actual_currency="USD")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Travel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Flights",
        )
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Trip",
            amount=100.0,
            expense_date=date(2026, 6, 1),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=100.0,
                    converted_at=date(2026, 5, 30),
                    conversion_donor_amount=50.0,
                    conversion_local_amount=100.0,
                )
            ],
        )

        ws = self._write(budget, categories=[category], lines=[line], expenses=[expense])
        rows = list(ws.iter_rows(values_only=True))

        assert rows[1][1] == "Travel"

    def test_no_expenses_still_writes_header_total_and_audit_line(self):
        budget = BudgetFactory.build(local_currency="GBP")

        ws = self._write(budget, exported_by="exporter@example.com")
        rows = list(ws.iter_rows(values_only=True))

        assert rows[0][0] == "Date"
        assert rows[1] == ("Total", None, None, None, 0.0, None, None, None, None)
        assert rows[2] == (None,) * 9
        assert rows[3][0] == "Generated by OpenGrantFlow · exporter@example.com"

    @pytest.mark.parametrize(
        "estimated_rate, local_amount",
        [(0.0, 100.0), (2.0, 0.0)],
        ids=["zero_estimated_rate", "zero_local_amount_conversion"],
    )
    def test_unusable_rate_writes_no_division_formula(self, estimated_rate, local_amount):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=estimated_rate
        )
        line = BudgetLineFactory.build(budget=budget, budget_id=budget.id, description="Travel")
        expense = ReportLineExpense(
            report_line_id=uuid4(),
            budget_line_id=line.id,
            description="Flight",
            amount=100.0,
            expense_date=date(2026, 6, 2),
            allocations=[
                ReportLineAllocationDetail(
                    amount_allocated=60.0,
                    converted_at=date(2026, 5, 30),
                    conversion_donor_amount=30.0,
                    conversion_local_amount=local_amount,
                )
            ],
        )

        ws = self._write(budget, lines=[line], expenses=[expense])

        for converted, rate in ws.iter_rows(min_row=2, min_col=6, max_col=7, values_only=True):
            if isinstance(converted, str) and "/G" in converted:
                assert isinstance(rate, float) and rate > 0


class TestGenerateBudgetExportWorkbook:
    def test_returns_valid_xlsx_roundtrip(self):
        budget = BudgetFactory.build()

        data = generate_budget_export_workbook(budget, [], [])

        wb = load_workbook(io.BytesIO(data))
        assert wb.sheetnames == [
            "Original Budget",
            "Budget vs. Report Dashboard",
            "List of Expenses",
        ]

    def test_full_layout_with_rate(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        cat1 = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Personnel", created_at=datetime(2026, 1, 1)
        )
        cat2 = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Travel", created_at=datetime(2026, 1, 2)
        )
        line1 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=cat1,
            category_id=cat1.id,
            description="Salaries",
            amount=1000.0,
            created_at=datetime(2026, 1, 1),
        )
        line2 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=cat2,
            category_id=cat2.id,
            description="Flights",
            amount=200.0,
            created_at=datetime(2026, 1, 2),
        )

        data = generate_budget_export_workbook(
            budget,
            [cat1, cat2],
            [line1, line2],
            organisation_name="Test Org",
            donor_name="Test Donor",
            exported_by="exporter@example.com",
            exported_at=datetime(2026, 9, 22, 14, 30, tzinfo=timezone.utc),
        )

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))

        # Header block; row 6 (Estimated Exchange Rate) is the formulas' rate cell ($B$6).
        # No extra_fields anywhere in this budget, so Amount/Estimate sit in B/C (no gap column).
        assert rows[0] == ("Organisation Name", "Test Org", None)
        assert rows[1] == ("Donor Name", "Test Donor", None)
        assert rows[2] == ("Project Name", budget.name, None)
        assert rows[4] == ("Budget Original Currency", "USD", None)
        assert rows[5] == ("Estimated Exchange Rate", 2.0, None)

        # Budget Summary: title doubles as the column header row; each category
        # references its own Detailed Budget subtotal cell, not a recomputed value.
        assert rows[8] == ("BUDGET SUMMARY", "Amount (GBP)", "Estimate (USD)")
        assert rows[9] == ("Personnel", "=B17", "=C17")
        assert rows[10] == ("Travel", "=B21", "=C21")
        assert rows[11] == ("TOTAL", "=SUM(B10:B11)", "=SUM(C10:C11)")
        assert ws.cell(row=10, column=1).border.top.style == "thin"
        assert ws.cell(row=10, column=1).border.left.style == "thin"
        assert ws.cell(row=11, column=3).border.bottom.style == "thin"
        assert ws.cell(row=11, column=3).border.right.style == "thin"
        assert ws.cell(row=12, column=1).border.top.style is None

        # Detailed Budget: category header row (no repeated column headers), lines,
        # then a SUM-formula subtotal row so hand-edits to a line amount recalculate.
        assert rows[13] == ("DETAILED BUDGET", None, None)
        assert rows[14] == ("Personnel", None, None)
        assert rows[15] == ("Salaries", 1000.0, "=B16/$B$6")
        assert rows[16] == ("Subtotal", "=SUM(B16:B16)", "=SUM(C16:C16)")
        assert rows[18] == ("Travel", None, None)
        assert rows[19] == ("Flights", 200.0, "=B20/$B$6")
        assert rows[20] == ("Subtotal", "=SUM(B20:B20)", "=SUM(C20:C20)")

        assert ws.cell(row=16, column=1).border.top.style == "thin"
        assert ws.cell(row=16, column=1).border.left.style == "thin"
        assert ws.cell(row=16, column=3).border.top.style == "thin"
        assert ws.cell(row=16, column=3).border.right.style == "thin"
        assert ws.cell(row=16, column=1).border.bottom.style == "thin"
        assert ws.cell(row=20, column=1).border.top.style == "thin"
        assert ws.cell(row=20, column=1).border.bottom.style == "thin"

        # Footer: total expenditures sums each category's own subtotal cell.
        assert rows[23] == ("Total expenditures", "=B17+B21", "=C17+C21")
        assert rows[27] == ("Authorised Signatory", None, None)
        assert rows[31] == ("Project contact person", None, None)
        assert ws.cell(row=27, column=1).border.top.style == "thin"
        assert ws.cell(row=31, column=1).border.top.style == "thin"

        assert rows[33] == (
            "Generated by OpenGrantFlow · exporter@example.com · 2026-09-22 14:30 UTC",
            None,
            None,
        )
        assert ws.cell(row=34, column=1).font.italic is True

        total_expenditures_cell = ws.cell(row=24, column=1)
        assert total_expenditures_cell.font.bold is True
        assert total_expenditures_cell.fill.fgColor.rgb == "00D9D9D9"

        assert ws.column_dimensions["A"].width == 26.63
        assert ws.column_dimensions["B"].width == 17.77
        assert ws["B16"].number_format == '#,##0.00" GBP"'
        assert ws["C16"].number_format == '#,##0.00" USD"'

    def test_blank_estimate_column_when_rate_unset(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=None
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Personnel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Salaries",
            amount=1000.0,
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        rows = list(load_workbook(io.BytesIO(data))["Original Budget"].iter_rows(values_only=True))
        assert rows[5] == ("Estimated Exchange Rate", None, None)
        assert rows[9] == ("Personnel", "=B16", None)
        assert rows[13] == ("Personnel", None, None)
        assert rows[14] == ("Salaries", 1000.0, None)
        assert rows[15] == ("Subtotal", "=SUM(B15:B15)", None)
        assert rows[18] == ("Total expenditures", "=B16", None)

    def test_single_extra_field_key_becomes_its_own_column(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line1 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="No extra",
            amount=1000.0,
            extra_fields=None,
            created_at=datetime(2026, 1, 1),
        )
        line2 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="AAAAAAA",
            amount=6000.0,
            extra_fields={"Description custom": "Hello world"},
            created_at=datetime(2026, 1, 2),
        )

        data = generate_budget_export_workbook(budget, [category], [line1, line2])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 4
        assert rows[8] == ("BUDGET SUMMARY", "Description custom", "Amount (GBP)", "Donor Estimate")
        assert rows[9] == ("Staff", None, "=C17", None)
        assert rows[13] == ("Staff", None, None, None)
        assert rows[14] == ("No extra", None, 1000, None)
        assert rows[15] == ("AAAAAAA", "Hello world", 6000, None)
        assert ws.column_dimensions["B"].width == 20.0

    def test_multiple_extra_field_keys_become_separate_columns(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Coordinator",
            amount=500.0,
            extra_fields={"Notes": "Approved", "Vendor": "Acme"},
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 5
        assert rows[8] == ("BUDGET SUMMARY", "Notes", "Vendor", "Amount (GBP)", "Donor Estimate")
        assert rows[14] == ("Coordinator", "Approved", "Acme", 500, None)

    def test_no_extra_fields_omits_extra_columns_entirely(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Salaries",
            amount=1000.0,
            extra_fields=None,
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 3
        assert rows[8] == ("BUDGET SUMMARY", "Amount (GBP)", "Donor Estimate")
        assert rows[13] == ("Staff", None, None)
        assert rows[14] == ("Salaries", 1000, None)

    def test_empty_category_still_shown_with_zero_subtotal(self):
        budget = BudgetFactory.build(local_currency="GBP")
        empty_category = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Contingency"
        )

        data = generate_budget_export_workbook(budget, [empty_category], [])

        rows = list(load_workbook(io.BytesIO(data))["Original Budget"].iter_rows(values_only=True))
        assert rows[9] == ("Contingency", "=B15", None)
        assert rows[13] == ("Contingency", None, None)
        assert rows[14] == ("Subtotal", 0.0, None)


async def _make_budget(db, owner_id=OWNER_ID, funding_customer_id=None):
    # Raw model, not BudgetFactory: setting its .budget relationship nulls the FK at flush.
    budget = BudgetModel(
        name="Test Budget",
        owner_id=owner_id,
        funding_customer_id=funding_customer_id,
        status=BudgetStatus.confirmed,
        start_date=date(2026, 1, 1),
        duration_months=12,
        local_currency="GBP",
        # tz-aware, matching the DateTime(timezone=True) column — catches openpyxl's
        # rejection of tz-aware datetimes, which only surfaces on an actual wb.save().
        confirmed_at=datetime(2026, 1, 5, tzinfo=timezone.utc),
    )
    db.add(budget)
    await db.commit()
    await db.refresh(budget)
    return budget


async def _make_category(db, budget_id, name="Personnel"):
    category = BudgetCategoryModel(budget_id=budget_id, name=name)
    db.add(category)
    await db.commit()
    await db.refresh(category)
    return category


async def _make_line(db, budget_id, category_id, amount=1000.0):
    line = BudgetLineModel(
        budget_id=budget_id, category_id=category_id, description="Salaries", amount=amount
    )
    db.add(line)
    await db.commit()
    await db.refresh(line)
    return line


@pytest.mark.anyio
class TestExportBudgetWorkbookRoute:
    async def test_owner_can_export(self, db, make_client):
        budget = await _make_budget(db)
        category = await _make_category(db, budget.id)
        await _make_line(db, budget.id, category.id)
        client = make_client(db=db, customer_id=OWNER_ID)

        with (
            patch(
                "app.services.excel_export_service.get_customer_cached",
                new_callable=AsyncMock,
                return_value={"name": "Test Org"},
            ),
            patch(
                "app.services.excel_export_service.get_users_by_ids_cached",
                new_callable=AsyncMock,
                return_value={},
            ),
        ):
            response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 200
        assert response.headers["content-type"] == (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        wb = load_workbook(io.BytesIO(response.content))
        assert wb.sheetnames == [
            "Original Budget",
            "Budget vs. Report Dashboard",
            "List of Expenses",
        ]

    async def test_funder_can_export(self, db, make_client):
        budget = await _make_budget(db, funding_customer_id=FUNDER_ID)
        client = make_client(db=db, customer_id=FUNDER_ID)

        with (
            patch(
                "app.services.excel_export_service.get_customer_cached",
                new_callable=AsyncMock,
                return_value={"name": "Test Org"},
            ),
            patch(
                "app.services.excel_export_service.get_users_by_ids_cached",
                new_callable=AsyncMock,
                return_value={},
            ),
        ):
            response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 200

    async def test_stranger_is_rejected(self, db, make_client):
        budget = await _make_budget(db)
        client = make_client(db=db, customer_id=STRANGER_ID)

        response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 400
