import io
from datetime import date, datetime, timezone
from unittest.mock import AsyncMock, patch
from uuid import uuid4

import pytest
from openpyxl import load_workbook

from app.models.budget import BudgetCategoryModel, BudgetLineModel, BudgetModel
from app.schemas.budget_schema import BudgetStatus
from app.services.excel_export_service import (
    _audit_line,
    _period_label,
    generate_budget_export_workbook,
)
from tests.factories.budget import BudgetCategoryFactory, BudgetFactory, BudgetLineFactory

OWNER_ID = str(uuid4())
FUNDER_ID = str(uuid4())
STRANGER_ID = str(uuid4())


class TestPeriodLabel:
    def test_none_start_date_returns_none(self):
        assert _period_label(None, 12) is None

    def test_formats_start_and_computed_end_month(self):
        assert _period_label(date(2026, 1, 1), 12) == "01/2026-12/2026"

    def test_no_duration_shows_start_month_only(self):
        assert _period_label(date(2026, 3, 15), None) == "03/2026"

    def test_zero_duration_shows_start_month_only(self):
        """0 is BudgetModel.duration_months's column default — same "unknown" case as None."""
        assert _period_label(date(2026, 3, 15), 0) == "03/2026"


class TestAuditLine:
    def test_includes_user_and_timestamp_when_both_known(self):
        exported_at = datetime(2026, 9, 22, 14, 30, tzinfo=timezone.utc)
        assert (
            _audit_line("a@b.com", exported_at)
            == "Generated by OpenGrantFlow · a@b.com · 2026-09-22 14:30 UTC"
        )

    def test_omits_missing_parts(self):
        assert _audit_line(None, None) == "Generated by OpenGrantFlow"


class TestGenerateBudgetExportWorkbook:
    def test_returns_valid_xlsx_roundtrip(self):
        budget = BudgetFactory.build()

        data = generate_budget_export_workbook(budget, [], [])

        wb = load_workbook(io.BytesIO(data))
        assert wb.sheetnames == ["Original Budget"]

    def test_full_layout_with_rate(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=2.0
        )
        cat1 = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Personnel", created_at=datetime(2026, 1, 1)
        )
        cat2 = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Travel", created_at=datetime(2026, 1, 2)
        )
        line1 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=cat1,
            category_id=cat1.id,
            description="Salaries",
            amount=1000.0,
            created_at=datetime(2026, 1, 1),
        )
        line2 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=cat2,
            category_id=cat2.id,
            description="Flights",
            amount=200.0,
            created_at=datetime(2026, 1, 2),
        )

        data = generate_budget_export_workbook(
            budget,
            [cat1, cat2],
            [line1, line2],
            organisation_name="Test Org",
            donor_name="Test Donor",
            exported_by="exporter@example.com",
            exported_at=datetime(2026, 9, 22, 14, 30, tzinfo=timezone.utc),
        )

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))

        # Header block; row 6 (Estimated Exchange Rate) is the formulas' rate cell ($B$6).
        # No extra_fields anywhere in this budget, so Amount/Estimate sit in B/C (no gap column).
        assert rows[0] == ("Organisation Name", "Test Org", None)
        assert rows[1] == ("Donor Name", "Test Donor", None)
        assert rows[2] == ("Project Name", budget.name, None)
        assert rows[4] == ("Estimated Currency", "USD", None)
        assert rows[5] == ("Estimated Exchange Rate", 2.0, None)

        # Budget Summary: title doubles as the column header row; each category
        # references its own Detailed Budget subtotal cell, not a recomputed value.
        assert rows[8] == ("BUDGET SUMMARY", "Amount (GBP)", "Estimate (USD)")
        assert rows[9] == ("Personnel", "=B17", "=C17")
        assert rows[10] == ("Travel", "=B21", "=C21")
        assert rows[11] == ("TOTAL", "=SUM(B10:B11)", "=SUM(C10:C11)")
        assert ws.cell(row=10, column=1).border.top.style == "thin"
        assert ws.cell(row=10, column=1).border.left.style == "thin"
        assert ws.cell(row=11, column=3).border.bottom.style == "thin"
        assert ws.cell(row=11, column=3).border.right.style == "thin"
        assert ws.cell(row=12, column=1).border.top.style is None

        # Detailed Budget: category header row (no repeated column headers), lines,
        # then a SUM-formula subtotal row so hand-edits to a line amount recalculate.
        assert rows[13] == ("DETAILED BUDGET", None, None)
        assert rows[14] == ("Personnel", None, None)
        assert rows[15] == ("Salaries", 1000.0, "=B16/$B$6")
        assert rows[16] == ("Subtotal", "=SUM(B16:B16)", "=SUM(C16:C16)")
        assert rows[18] == ("Travel", None, None)
        assert rows[19] == ("Flights", 200.0, "=B20/$B$6")
        assert rows[20] == ("Subtotal", "=SUM(B20:B20)", "=SUM(C20:C20)")

        assert ws.cell(row=16, column=1).border.top.style == "thin"
        assert ws.cell(row=16, column=1).border.left.style == "thin"
        assert ws.cell(row=16, column=3).border.top.style == "thin"
        assert ws.cell(row=16, column=3).border.right.style == "thin"
        assert ws.cell(row=16, column=1).border.bottom.style == "thin"
        assert ws.cell(row=20, column=1).border.top.style == "thin"
        assert ws.cell(row=20, column=1).border.bottom.style == "thin"

        # Footer: total expenditures sums each category's own subtotal cell.
        assert rows[23] == ("Total expenditures", "=B17+B21", "=C17+C21")
        assert rows[27] == ("Authorised Signatory", None, None)
        assert rows[31] == ("Project contact person", None, None)
        assert ws.cell(row=27, column=1).border.top.style == "thin"
        assert ws.cell(row=31, column=1).border.top.style == "thin"

        assert rows[33] == (
            "Generated by OpenGrantFlow · exporter@example.com · 2026-09-22 14:30 UTC",
            None,
            None,
        )
        assert ws.cell(row=34, column=1).font.italic is True

        total_expenditures_cell = ws.cell(row=24, column=1)
        assert total_expenditures_cell.font.bold is True
        assert total_expenditures_cell.fill.fgColor.rgb == "00D9D9D9"

        assert ws.column_dimensions["A"].width == 26.63
        assert ws.column_dimensions["B"].width == 17.77
        assert ws["B16"].number_format == '#,##0.00" GBP"'
        assert ws["C16"].number_format == '#,##0.00" USD"'

    def test_blank_estimate_column_when_rate_unset(self):
        budget = BudgetFactory.build(
            local_currency="GBP", actual_currency="USD", estimated_exchange_rate=None
        )
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Personnel")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Salaries",
            amount=1000.0,
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        rows = list(load_workbook(io.BytesIO(data))["Original Budget"].iter_rows(values_only=True))
        assert rows[5] == ("Estimated Exchange Rate", None, None)
        assert rows[9] == ("Personnel", "=B16", None)
        assert rows[13] == ("Personnel", None, None)
        assert rows[14] == ("Salaries", 1000.0, None)
        assert rows[15] == ("Subtotal", "=SUM(B15:B15)", None)
        assert rows[18] == ("Total expenditures", "=B16", None)

    def test_single_extra_field_key_becomes_its_own_column(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line1 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="No extra",
            amount=1000.0,
            extra_fields=None,
            created_at=datetime(2026, 1, 1),
        )
        line2 = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="AAAAAAA",
            amount=6000.0,
            extra_fields={"Description custom": "Hello world"},
            created_at=datetime(2026, 1, 2),
        )

        data = generate_budget_export_workbook(budget, [category], [line1, line2])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 4
        assert rows[8] == ("BUDGET SUMMARY", "Description custom", "Amount (GBP)", "Donor Estimate")
        assert rows[9] == ("Staff", None, "=C17", None)
        assert rows[13] == ("Staff", None, None, None)
        assert rows[14] == ("No extra", None, 1000, None)
        assert rows[15] == ("AAAAAAA", "Hello world", 6000, None)
        assert ws.column_dimensions["B"].width == 20.0

    def test_multiple_extra_field_keys_become_separate_columns(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Coordinator",
            amount=500.0,
            extra_fields={"Notes": "Approved", "Vendor": "Acme"},
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 5
        assert rows[8] == (
            "BUDGET SUMMARY", "Notes", "Vendor", "Amount (GBP)", "Donor Estimate"
        )
        assert rows[14] == ("Coordinator", "Approved", "Acme", 500, None)

    def test_no_extra_fields_omits_extra_columns_entirely(self):
        budget = BudgetFactory.build(local_currency="GBP")
        category = BudgetCategoryFactory.build(budget=budget, budget_id=budget.id, name="Staff")
        line = BudgetLineFactory.build(
            budget=budget,
            budget_id=budget.id,
            category=category,
            category_id=category.id,
            description="Salaries",
            amount=1000.0,
            extra_fields=None,
        )

        data = generate_budget_export_workbook(budget, [category], [line])

        ws = load_workbook(io.BytesIO(data))["Original Budget"]
        rows = list(ws.iter_rows(values_only=True))
        assert ws.max_column == 3
        assert rows[8] == ("BUDGET SUMMARY", "Amount (GBP)", "Donor Estimate")
        assert rows[13] == ("Staff", None, None)
        assert rows[14] == ("Salaries", 1000, None)

    def test_empty_category_still_shown_with_zero_subtotal(self):
        budget = BudgetFactory.build(local_currency="GBP")
        empty_category = BudgetCategoryFactory.build(
            budget=budget, budget_id=budget.id, name="Contingency"
        )

        data = generate_budget_export_workbook(budget, [empty_category], [])

        rows = list(load_workbook(io.BytesIO(data))["Original Budget"].iter_rows(values_only=True))
        assert rows[9] == ("Contingency", "=B15", None)
        assert rows[13] == ("Contingency", None, None)
        assert rows[14] == ("Subtotal", 0.0, None)


async def _make_budget(db, owner_id=OWNER_ID, funding_customer_id=None):
    # Raw model, not BudgetFactory: setting its .budget relationship nulls the FK at flush.
    budget = BudgetModel(
        name="Test Budget",
        owner_id=owner_id,
        funding_customer_id=funding_customer_id,
        status=BudgetStatus.confirmed,
        start_date=date(2026, 1, 1),
        duration_months=12,
        local_currency="GBP",
    )
    db.add(budget)
    await db.commit()
    await db.refresh(budget)
    return budget


async def _make_category(db, budget_id, name="Personnel"):
    category = BudgetCategoryModel(budget_id=budget_id, name=name)
    db.add(category)
    await db.commit()
    await db.refresh(category)
    return category


async def _make_line(db, budget_id, category_id, amount=1000.0):
    line = BudgetLineModel(
        budget_id=budget_id, category_id=category_id, description="Salaries", amount=amount
    )
    db.add(line)
    await db.commit()
    await db.refresh(line)
    return line


@pytest.mark.anyio
class TestExportBudgetWorkbookRoute:
    async def test_owner_can_export(self, db, make_client):
        budget = await _make_budget(db)
        category = await _make_category(db, budget.id)
        await _make_line(db, budget.id, category.id)
        client = make_client(db=db, customer_id=OWNER_ID)

        with (
            patch(
                "app.services.excel_export_service.get_customer_cached",
                new_callable=AsyncMock,
                return_value={"name": "Test Org"},
            ),
            patch(
                "app.services.excel_export_service.get_users_by_ids_cached",
                new_callable=AsyncMock,
                return_value={},
            ),
        ):
            response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 200
        assert response.headers["content-type"] == (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        wb = load_workbook(io.BytesIO(response.content))
        assert wb.sheetnames == ["Original Budget"]

    async def test_funder_can_export(self, db, make_client):
        budget = await _make_budget(db, funding_customer_id=FUNDER_ID)
        client = make_client(db=db, customer_id=FUNDER_ID)

        with (
            patch(
                "app.services.excel_export_service.get_customer_cached",
                new_callable=AsyncMock,
                return_value={"name": "Test Org"},
            ),
            patch(
                "app.services.excel_export_service.get_users_by_ids_cached",
                new_callable=AsyncMock,
                return_value={},
            ),
        ):
            response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 200

    async def test_stranger_is_rejected(self, db, make_client):
        budget = await _make_budget(db)
        client = make_client(db=db, customer_id=STRANGER_ID)

        response = client.get(f"/api/v1/budgets/{budget.id}/export.xlsx")

        assert response.status_code == 400
